### ISSUE TITLE
출퇴근 1회씩 한 후에 출퇴근이 안되는 버그

### ISSUE THREAD

**Issue by cheonjaeung** [g-bridge-etners/g-bridge-etners#26]
### 발생위치
FragmentHome.java

### 증상
출근과 퇴근 최소 1회씩은 정상적으로 처리가 되지만 그 이후에는 에러코드 418 발생. (https://github.com/g-bridge-etners/rest-api#%EC%B6%9C%ED%87%B4%EA%B7%BC-%EA%B8%B0%EB%8A%A5-patch--commutecheck 참고)

**Comment by Tao-Kim** [comment]
이거 서버에서 하루 단위로 체크하는데 하루에 출근 되있고 퇴근 되있고 기록이 있어요.
이미 퇴근 완료한 날짜에 다시 퇴근 시도해서 418 반환된건데

로직 변경할까요?

**Comment by cheonjaeung** [comment]
아 하루단위로 체크하는 거였군요. 모르고 버그인줄 알았습니다. 굳이 로직 안바꿔도 괜찮을거 같아요.

**Comment by Tao-Kim** [comment]
넵 감사합니다
